### PR TITLE
[nan-753] bundle deps dynamically

### PR DESCRIPTION
**Pull request by khaliqgant**
## Describe your changes
bundleDependencies is causing issues with package resolution in remote environments so dynamically add it to publish

## Issue ticket number and link
NAN-753

## Checklist before requesting a review (skip if just adding/editing APIs & templates)
- [ ] I added tests, otherwise the reason is: 
- [ ] I added observability, otherwise the reason is:
- [ ] I added analytics, otherwise the reason is:

### CODE REVIEW

**Comment by bodinsamuel** [comment]
The image seems to contain the package now 👌🏻

**Comment by bodinsamuel** [comment]
Merging for you

**Comment by khaliqgant** [comment]
Thanks for merging. My availability is spotty this week

**Comment by bodinsamuel** [comment]
No worries, completely understandable ☺️

**Pull request merged**
