### PR TITLE
fix(ui): improve code snippets

### PR DESCRIPTION
**Pull request by bodinsamuel**
## Describe your changes

Fixes https://linear.app/nango/issue/NAN-1412/records-snippets-indentation-is-broken
Fixes https://linear.app/nango/issue/NAN-1538/find-a-way-to-generate-multi-language-snippets

- Improve code generation using a `httpsnippet` library
It's not perfect perfect, especially for `body` but good enough. 

- Improve indentation for template snippets

> [!NOTE] 
> This does not improve code generation for response and record of an enabled script. This is because we produce a typescript object and not a valid JSON object (mostly because of optional `?`) 

Screenshot 2024-09-09 at 16 20 00

### CODE REVIEW

**Review by TBonnin — APPROVED** [review]
works as intented

Screenshot 2024-09-09 at 20 19 42

`go` developers are gonna complain that we don't encourage good error handling 😆

**Comment by bodinsamuel** [comment]
> go developers are gonna complain that we don't encourage good error handling 😆

Ahah 🤭 you can address your complains to `httpsnippet` :p

**Comment by TBonnin** [comment]
> > go developers are gonna complain that we don't encourage good error handling 😆
> 
> Ahah 🤭 you can address your complains to `httpsnippet` :p

in their defence they do support it ;) https://github.com/Kong/httpsnippet/wiki/Targets#native

**Comment by bodinsamuel** [comment]
Oh let me check that

**Pull request merged**
