### PR TITLE
fix: update error message for provider key missing

### PR DESCRIPTION
**Pull request by kndwin**
## Describe your changes
I spent like an hour trying to understand where to pass this in (had to look through the source code) and thought it'll be an easy PR to push

## Checklist before requesting a review (skip if just adding/editing APIs & templates)
- [ ] I added tests, otherwise the reason is: 
- [ ] I added observability, otherwise the reason is:
- [ ] I added analytics, otherwise the reason is:

### CODE REVIEW

**Comment by bastienbeurier** [comment]
Thanks for contributing this @kndwin and sorry for the confusion!

**Review by bodinsamuel — APPROVED** [review]
Thanks for your contribution @kndwin 
Can I ask what scenario lead to this? Because this error message is shown only when no syncs or actions matched anyway

**Comment by kndwin** [comment]
Yeah it turns out my <sync_name> I passed in was misspelled anyway 

nango dryrun <sync_name> <connection_id> 

The error though made me think I didn't pass in the provider config key so went on a long journey to realised I made 2 errors (not passing in --integration-id and misspelling the <sync_name>)

After passing in the --integration-id I had a new error (The sync/action was not executed (I think it was that)) which prompted me to just console log all the args inside the node_module folder of the nango global file and then I noticed my error

(Would be nice actually to suggest the closest name but probably a feature request)

**Comment by bodinsamuel** [comment]
yes indeed we should probably suggest a list of syncs if nothing matched. I'll merge this as-is and note to improve this scenario 👌🏻

**Pull request merged**
