### PR TITLE
fix(node-client): fix list records with modifiedAfter

### PR DESCRIPTION
**Pull request by descampsk**
## Describe your changes

Use delta and modified_after instead of modifiedAfter

## Issue ticket number and link

Fix https://github.com/NangoHQ/nango/issues/1970

## Checklist before requesting a review (skip if just adding/editing APIs & templates)
- [ ] I added tests, otherwise the reason is: 
- [ ] I added observability, otherwise the reason is:
- [ ] I added analytics, otherwise the reason is:

### CODE REVIEW

**Comment by bodinsamuel** [comment]
hey @descampsk 
Thanks a lot for taking the time to report and providing a fix. We are taking over your PR just to merge it quickly. 

For clarification, `delta` is deprecated and was a date not a boolean. We just renamed delta to modified_after for clarification, that's why they were interchangeable.

**Comment by bodinsamuel** [comment]
Fixed by #1972

**Comment by descampsk** [comment]
hey @bodinsamuel 

Thanks but we still have to have delta set which is not indicated in the documentation https://docs.nango.dev/integrate/guides/sync-data-from-an-api#fetch-the-latest-data.

Should we have `${(delta || modifiedAfter) ? modified_after=${modifiedAfter || delta}` instead ?

**Comment by bodinsamuel** [comment]
You are right indeed, we missed this details! Thanks for raising 🙏🏻

**Comment by bodinsamuel** [comment]
The new version `0.39.16` has been released 👍🏻

**Pull request closed without merging**
