### PR TITLE
WIP - Garmin integration and API provider

### PR DESCRIPTION
**Pull request by henrymgarrett**
## Describe your changes
Integrating the Garmin API provider

## Checklist before requesting a review (skip if just adding/editing APIs & templates)
- [ ] I added tests, otherwise the reason is: 
- [ ] I added observability, otherwise the reason is:
- [ ] I added analytics, otherwise the reason is:

### CODE REVIEW

**Comment by bastienbeurier** [comment]
Thank you for contributing this @henrymgarrett. 

Quick question: could you test it by any chance?

**Comment by henrymgarrett** [comment]
> Thank you for contributing this @henrymgarrett.
> 
> Quick question: could you test it by any chance?

@bastienbeurier I was not able to get it working (hence why I reached out for help :) ).  The error I'm seeing when running locally is listed below.  Any insight you can lend?

```
nango-server  | 20:20:17.259 info (elasticsearch) [debug] operation({"id":"5","source":"internal","level":"info","operation":{"type":"auth","action":"create_connection"},"type":"log","message":"Create connection via OAuth","title":null,"code":null,"state":"running","accountId":0,"accountName":"My Organization","environmentId":2,"environmentName":"dev","integrationId":null,"integrationName":null,"providerName":null,"connectionId":null,"connectionName":null,"syncConfigId":null,"syncConfigName":null,"jobId":null,"userId":null,"parentId":null,"error":null,"request":null,"response":null,"meta":null,"createdAt":"2024-06-17T20:20:17.259Z","updatedAt":"2024-06-17T20:20:17.259Z","startedAt":"2024-06-17T20:20:17.259Z","endedAt":null,"expiresAt":"2024-06-17T20:25:17.259Z"}) 
nango-server  | 20:20:17.263 info (Activity) Authorization URL request from the client 
nango-server  | 20:20:17.266 info (elasticsearch) [dry] log: Authorization URL request from the client 
nango-server  | 20:20:17.272 info (elasticsearch) [dry] enrich({"integrationId":1,"integrationName":"garmin","providerName":"garmin"})(5) 
nango-server  | 20:20:17.273 info (Activity) OAuth callback URL was retrieved 
nango-server  | 20:20:17.275 info (elasticsearch) [dry] log: OAuth callback URL was retrieved { meta: { url: 'http://localhost:3003/oauth/callback?state=03179780-2ce7-11ef-8699-bbebb34fc3b2' } }
nango-server  | 20:20:17.472 error (ErrorManager) Exception caught: {"name":"Error","message":"token_retrieval_error","stack":"Error: token_retrieval_error\n    at OAuthController.oauth1Request (file:///usr/nango-server/src/packages/server/dist/controllers/oauth.controller.js:746:33)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"} 
nango-server  | 20:20:17.473 error (Activity) Error storing/retrieving the token. 
nango-server  | 20:20:17.481 error (elasticsearch) [dry] log: Error storing/retrieving the token. { error: { message: 'unknown error', name: 'Unknown Error' }, meta: { url: 'http://localhost:3003/oauth/callback?state=03179780-2ce7-11ef-8699-bbebb34fc3b2' } }
```

**Comment by bastienbeurier** [comment]
Understood, thank you for the details!

**Comment by henrymgarrett** [comment]
Closed in lieu of https://github.com/NangoHQ/nango/pull/2445

**Comment by henrymgarrett** [comment]
Closed in lieu of https://github.com/NangoHQ/nango/pull/2445

**Comment by henrymgarrett** [comment]
Closed in lieu of https://github.com/NangoHQ/nango/pull/2445

**Pull request closed without merging**
