### PR TITLE
Enable server rate limit

### PR DESCRIPTION
**Pull request by TBonnin**
## Describe your changes

Enabling rate-limiting (was only logging so far). 
Since I pushed the memoization of getConnection yesterday, no rate limiting has been logged so it should not impact anybody.

followup of https://github.com/NangoHQ/nango/pull/1708

### CODE REVIEW

**Review by khaliqgant — COMMENTED** [review]
Should we give this more time? For some customers syncs run just once a week so are we really be sure that this won't affect anyone? I would suggest waiting or at least announce it

**Review by bodinsamuel — APPROVED** [review]
Let's go 👍🏻 
Should we document that somewhere? @bastienbeurier

**Comment by TBonnin** [comment]
> Should we give this more time? For some customers syncs run just once a week so are we really be sure that this won't affect anyone? I would suggest waiting or at least announce it

Sure. we can wait. @bastienbeurier what do you think.
wrt the doc I created a ticket https://linear.app/nango/issue/NAN-486/document-rate-limit

**Comment by bastienbeurier** [comment]
Thanks for pointing out @bodinsamuel and for creating a ticket @TBonnin. I'll take care of it since I'm deep in the docs these days.

**Comment by TBonnin** [comment]
@khaliqgant after how long would you feel confident to merge/release this PR?

**Comment by khaliqgant** [comment]
> @khaliqgant after how long would you feel confident to merge/release this PR?

I would say a week so we can get a picture, so I guess that would be Thursday?

**Pull request merged**
