### PR TITLE
fix: added new scripts to gen source-maps on install

### LINKED ISSUE #385: Missing js.map in Frontend SDK
Using the frontend SDK in a React app shows the following error:
Screenshot 2023-03-21 at 06 36 30

### PR DESCRIPTION
**Pull request by Chakravarthy7102**
fixes #385

1. Added new postinstall script on `frontend` to generate *.map files for js to minified js.
2. Also updated  `prettier-format` script to be able to run in windows environment.

Screenshot (13)

I would like to break issue #385 into two parts for getting resolved. 

1. update the `@nangohq/frontend` lib with latest changes.
2. updating the package in `webapp` to latest release.

 Thanks! 😸

### CODE REVIEW

**Comment by bastienbeurier** [comment]
Thank you for taking this on!

My understanding was that source maps are being generated already: 
Screenshot 2023-04-18 at 10 15 01

But we are not including them in the published npm package 
Screenshot 2023-04-18 at 10 14 50

Apparently, it's actually better not to include them in the npm package (cf. ChatGPT's answer :D):
Screenshot 2023-04-18 at 10 16 41

This Stackoverflow [answer](https://stackoverflow.com/a/70834076) suggests that this is a bug with Webpack.

**Comment by Chakravarthy7102** [comment]
> Thank you for taking this on!
> 
> My understanding was that source maps are being generated already: Screenshot 2023-04-18 at 10 15 01
> 
> But we are not including them in the published npm package Screenshot 2023-04-18 at 10 14 50
> 
> Apparently, it's actually better not to include them in the npm package (cf. ChatGPT's answer :D): Screenshot 2023-04-18 at 10 16 41
> 
> This Stackoverflow [answer](https://stackoverflow.com/a/70834076) suggests that this is a bug with Webpack.

[answer](https://stackoverflow.com/a/70834076) Yup, This is indeed bug with webpack but there is no PR currently that resoving this issues and I see that there many people with the same problem.
Either we should go with the HACKS suggested in this stackoverflow thread or we should include .map files in the npm package
1. first solution is not a great one IMO
2. the second solution will increse the budle with uncessary files!! which is super bad.

**Comment by Chakravarthy7102** [comment]
> Thank you for taking this on!
> 
> My understanding was that source maps are being generated already: Screenshot 2023-04-18 at 10 15 01
> 
> But we are not including them in the published npm package Screenshot 2023-04-18 at 10 14 50
> 
> Apparently, it's actually better not to include them in the npm package (cf. ChatGPT's answer :D): Screenshot 2023-04-18 at 10 16 41
> 
> This Stackoverflow [answer](https://stackoverflow.com/a/70834076) suggests that this is a bug with Webpack.



> Thank you for taking this on!
> 
> My understanding was that source maps are being generated already: Screenshot 2023-04-18 at 10 15 01
> 
> But we are not including them in the published npm package Screenshot 2023-04-18 at 10 14 50
> 
> Apparently, it's actually better not to include them in the npm package (cf. ChatGPT's answer :D): Screenshot 2023-04-18 at 10 16 41
> 
> This Stackoverflow [answer](https://stackoverflow.com/a/70834076) suggests that this is a bug with Webpack.

When I ran the project in my local env I did't notice any map files generated in root `node_modules` may be I'm missing something, However suggested solution in this PR generates map files on the clinet only when the package is installed!,

**Review by bastienbeurier — APPROVED** [review]

**Comment by bastienbeurier** [comment]
Sounds good, let's go with this. This is ready to merge, there's just a remaining conflict. Thank you for the contribution!

**Pull request merged**
