### PR TITLE
fix(logs): cron delete old logs

### PR DESCRIPTION
**Pull request by bodinsamuel**
## Describe your changes

Fixes NAN-794

- Cron: delete old logs (15 default retention)

### CODE REVIEW

**Review by TBonnin — COMMENTED** [review]
Can deleting old logs be done by dropping old indexes?

**Review by khaliqgant — APPROVED** [review]
Looks good but curious about Thomas' question as well.

**Comment by bodinsamuel** [comment]
Logs are currently stored in a single index, I didn't wanted to over engineer this rn and we often dont know how long a sync run so it would make the query a little more complexe to handle

**Comment by TBonnin** [comment]
> Logs are currently stored in a single index, I didn't wanted to over engineer this rn and we often dont know how long a sync run so it would make the query a little more complexe to handle

I think you can define a wildcard pattern to query over multiple indexes. This way we can have daily indexes (`logs-20240430`, `logs-20240501`, etc...) with a `logs-*` pattern. Couple that with an index lifetime management rules to drop indexes after 14 days.

**Comment by bodinsamuel** [comment]
I messed up this branch :| closing

**Pull request closed without merging**
