### PR TITLE
[nan-862] add level: 'warn' | 'info' | 'error' so it can be filtered

### PR DESCRIPTION
**Pull request by khaliqgant**
## Describe your changes
Add level property for filtering

## Issue ticket number and link
NAN-862

## Checklist before requesting a review (skip if just adding/editing APIs & templates)
- [ ] I added tests, otherwise the reason is: 
- [ ] I added observability, otherwise the reason is:
- [ ] I added analytics, otherwise the reason is:

### CODE REVIEW

**Review by TBonnin — COMMENTED** [review]
how does that work? is `isError` a ddog logs api field?

**Comment by khaliqgant** [comment]
> how does that work? is `isError` a ddog logs api field?

It isn't anything specific to datadog but rather just allows another tag to filter by. From what I saw in the datadog documentation there isn't an easy way to set an error label without changing the pipeline the log streams to.

**Review by TBonnin — COMMENTED** [review]
can we have a `level` field instead so we can pass `error | info | warn`?

**Comment by khaliqgant** [comment]
> can we have a `level` field instead so we can pass `error | info | warn`?

Yup, probably a better idea. I'll adjust, thanks.

**Comment by khaliqgant** [comment]
> > can we have a `level` field instead so we can pass `error | info | warn`?
> 
> Yup, probably a better idea. I'll adjust, thanks.

Updated with https://github.com/NangoHQ/nango/pull/2130/commits/aa996499ece6a02dc1a1d7eb0ec549000580fe21

**Review by TBonnin — COMMENTED** [review]
I would also enforce the acceptable values with something like:
```
    public async log(
        eventId: string,
        message: string,
        operation: string,
        context: Record<string, string> & { level?: 'info' | 'error' | 'warn' } = {},
        additionalTags = ''
    ) {
        const additionalProperties = {
            ...context,
            level: context.level || 'info'
        };
        const params: v2.LogsApiSubmitLogRequest = {
            body: [
                {
                    ddsource: 'web',
                    ddtags: `${eventId}, environment:${process.env['NODE_ENV']}, ${additionalTags}`,
                    message,
                    service: operation,
                    additionalProperties: additionalProperties
                }
            ]
        };

        await this.logInstance?.submitLog(params);
    }

```

**Pull request merged**
