### PR TITLE
fix(package): pin more internal package

### PR DESCRIPTION
**Pull request by bodinsamuel**
## Describe your changes

Followup #2439 

- Remove the non-exact install but forgot to remove `^` from the publish script

### CODE REVIEW

**Review by khaliqgant — APPROVED** [review]

**Review by TBonnin — APPROVED** [review]

**Comment by bodinsamuel** [comment]
The CI is failing not sure why

**Comment by bodinsamuel** [comment]
@khaliqgant do you have any clue why this error would happen? 
https://github.com/NangoHQ/nango/actions/runs/11739648559/job/32704887491?pr=2955
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@nangohq/database' imported from /home/runner/work/nango/nango/node_modules/@nangohq/shared/dist/services/external-webhook.service.js
```

Keep coming back to it but can't find anything, I'm that close to merging this without solving the issue 😓

**Comment by khaliqgant** [comment]
> @khaliqgant do you have any clue why this error would happen? https://github.com/NangoHQ/nango/actions/runs/11739648559/job/32704887491?pr=2955
> 
> ```
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@nangohq/database' imported from /home/runner/work/nango/nango/node_modules/@nangohq/shared/dist/services/external-webhook.service.js
> ```
> 
> Keep coming back to it but can't find anything, I'm that close to merging this without solving the issue 😓

Probably an issue with npm packing, can you reproduce by trying to package and push the package locally to github?

**Comment by bodinsamuel** [comment]
I will merge that as-is, but the most important fix is missing. 
Can't pin shared in the CLI, not sure why it breaks only in the CI

**Pull request merged**
