### PR TITLE
fix(ui): syncs use table and correct button depending on sync_type

### PR DESCRIPTION
**Pull request by bodinsamuel**
## Describe your changes

Fixes https://linear.app/nango/issue/NAN-1275/button-to-trigger-incremental-execution-should-show-for-full-refresh

- getSyncs now returns `sync_type`
- UI: Split component SyncRow
- UI: Use Table component 
- UI: Show another button when we want to trigger a sync of type `full`

### CODE REVIEW

**Review by khaliqgant — COMMENTED** [review]
Is it the intention that the design changes?

Before
image

After
image

Also the modal changed and doesn't close on completion:

Before:

https://github.com/NangoHQ/nango/assets/1724137/71627177-e96b-46c3-8e0f-972e93953b1a



After:

https://github.com/NangoHQ/nango/assets/1724137/96206355-ce11-43d2-a009-500174d709bc

**Comment by bodinsamuel** [comment]
> Is it the intention that the design changes?

That's the new table design yes, however I'm sure there will be some tweaks in the future depending on the view.
It's just missing the border that is an other pending PR

> Also the modal changed and doesn't close on completion:

Thanks forgot to do that 👌🏻

**Comment by khaliqgant** [comment]
Should the modal buttons be to the right or to the left? And the `c` in `Cancel` should be capitalized

Before:
image


After:
image

**Comment by khaliqgant** [comment]
> Should the modal buttons be to the right or to the left? And the `c` in `Cancel` should be capitalized
> 
> Before: image
> 
> After: image

In figma it looks like it is to the right which I agree looks better

image


but the update modal doesn't really match that design. The white is too harsh on the outline and no border is around the "cancel" button

**Comment by bodinsamuel** [comment]
Good point about the border and button, fixed that 👌🏻

**Review by khaliqgant — APPROVED** [review]
Looks good

**Pull request merged**
