### PR TITLE
fix(release): automatic release publishing

### PR DESCRIPTION
**Pull request by bodinsamuel**
## Describe your changes

Fixes NAN-632

- Add an **automated release process to publish Changelog** and create a GitHub release
I have tested locally and with my personal GitHub token, it does create the commit and GH release, but we all know it's hard to test github actions.

> [!INFO]
> We all need to use conventional commit to make this release process helpful. https://www.conventionalcommits.org/en/v1.0.0/ However since we input the version it's not factually correct yet. Ultimately the script should determine the next version on its own.

### CODE REVIEW

**Review by TBonnin — COMMENTED** [review]
Can we add a `prepare-commit-msg` hook to encourage us to write conventional commit message and even narrow down its specs. Ex:
```
feat|fix|chore(SCOPE): DESCRIPTION

[BODY]
```

**Comment by bastienbeurier** [comment]
Nice! Thank you for taking care of this 🙏

**Comment by bodinsamuel** [comment]
> Can we add a prepare-commit-msg hook to encourage us to write conventional commit message and even narrow down its specs. Ex:

It's a bit painful per commit, but we can add something for PR title yes. Let me check

**Comment by bodinsamuel** [comment]
@TBonnin done 👍🏻

**Review by TBonnin — APPROVED** [review]

**Review by khaliqgant — APPROVED** [review]
Can we document somewhere what the updated way of doing things should be?

**Comment by bodinsamuel** [comment]
> Can we document somewhere what the updated way of doing things should be?

Added a line in contributing, not sure what else should be done

**Pull request merged**
