### PR TITLE
fix(api): /sync/status returns execution frequency

### PR DESCRIPTION
**Pull request by bodinsamuel**
## Describe your changes

`GET /sync/status` now returns the effective frequency of the sync

### CODE REVIEW

**Comment by bodinsamuel** [comment]
I don't have access to mintlify so not sure what is blocking

**Comment by TBonnin** [comment]
> I don't have access to mintlify so not sure what is blocking

you can install mintlify locally and run `npm run docs` to build the docs locally

**Comment by bodinsamuel** [comment]
Oh great I didn't know that thanks. 
It works on my machine, no luck :D

**Review by khaliqgant — CHANGES_REQUESTED** [review]
Looks good! Needs an update the [node sdk docs](https://docs.nango.dev/sdks/node#sync-status) too

**Comment by bodinsamuel** [comment]
Updated 👍🏻

**Review by khaliqgant — APPROVED** [review]

**Pull request merged**
