### PR TITLE
Add Contentstack integration

### PR DESCRIPTION
**Pull request by Khaalidsub**

### CODE REVIEW

**Comment by bastienbeurier** [comment]
Thank you for contributing this @Khaalidsub! Could you test that it works?

**Comment by bastienbeurier** [comment]
Would you mind doing a follow up PR with an entry in the docs for this new integration please? 

It's under `docs/docs/providres` and you'd have to create a `contentstack.md` file with a similar structure than the other ones. Thanks!

**Comment by bastienbeurier** [comment]
Oh sorry, I moved the `providers.yaml` file to a different folder today. So you have to resolve that before I can merge your PR.

**Comment by bastienbeurier** [comment]
Let me know if you need any assistance on this!

**Comment by Khaalidsub** [comment]
@bastienbeurier yes I have tested it and it works well
I will will create a new pr for this after merging the new changes

**Pull request closed without merging**
