### PR TITLE
fix(Provider): proxy is optional

### PR DESCRIPTION
**Pull request by bodinsamuel**
## Describe your changes

Following the eslint upgrade it now removes unnecessary `?` so it broke my setup locally. Proxy is optional because of `unauthenticated` provider.

- Set `proxy` as optional

### CODE REVIEW

**Comment by khaliqgant** [comment]
My sense is that the types aren’t always completely correct and so removing the optional ? is going to break more things. The linter gives us false confidence to delete ? willy nilly — so to speak

**Comment by bodinsamuel** [comment]
> My sense is that the types aren’t always completely correct and so removing the optional ? is going to break more things. > The linter gives us false confidence to delete ? willy nilly — so to speak

we can disable the rule for the moment, wdyt?

**Comment by khaliqgant** [comment]
> > My sense is that the types aren’t always completely correct and so removing the optional ? is going to break more things. > The linter gives us false confidence to delete ? willy nilly — so to speak
> 
> we can disable the rule for the moment, wdyt?

Yeah I think so. Don’t want it to bite us

**Comment by bodinsamuel** [comment]
Disabled 👌🏻  but we should aim to have better types, this kind of unnecessary condition also makes the code slower and shaky

**Review by khaliqgant — APPROVED** [review]

**Comment by khaliqgant** [comment]
> Disabled 👌🏻 but we should aim to have better types, this kind of unnecessary condition also makes the code slower and shaky

100% agree

**Comment by khaliqgant** [comment]
> My sense is that the types aren’t always completely correct and so removing the optional ? is going to break more things. The linter gives us false confidence to delete ? willy nilly — so to speak

Case in point: https://github.com/NangoHQ/nango/pull/2099 as reported https://nango-community.slack.com/archives/C04ABR352H0/p1714974911347219

**Pull request merged**
