### PR TITLE
refactor(webapp): dashboard layout

### PR DESCRIPTION
**Pull request by ComfortablyCoding**
This PR refactors the webapp dashboard extracting common design patters into the layout component and improves styling.

## Patterns extracted
- page content padding
- page content max width

## Style improvements
- utilizes flex for dashboard layout instead of position. This removes the need for
  - margin top on sidebar menu
  - margin left on page content
- improves integration list table columns by having them re-size somewhat dynamically
  - This should resolve the x-axis scroll bar reported in #1045

### CODE REVIEW

**Comment by khaliqgant** [comment]
Thanks for your thorough work here @ComfortablyCoding! We'll check this out in the next couple of days!

**Review by khaliqgant — APPROVED** [review]
Awesome, thanks!

**Comment by khaliqgant** [comment]
Can you just resolve the conflicts here and this will be good to go @ComfortablyCoding. Thanks!

**Comment by ComfortablyCoding** [comment]
@khaliqgant Should be good to go.

**Comment by khaliqgant** [comment]
Looked at this a bit closer and a couple of issues with compressing the able arise:

Before the change
image

After the change
image


Before the change
image


After the change
image


With the compressed table the sync information cuts into the rows and in the second screenshot the text overflows the button

**Comment by ComfortablyCoding** [comment]
Ok, I will have a look. What screen size were you checking this on?

P.S. 
Is their some way to run/test this easily on locale? I have been doing it via running local webapp while at the same time running the docker image to have the backend. This is quite tedious.

P.P.S
Are their any opinions for mobile view? I believe most of these issues stem from the table having too many columns at small/medium screen size.

**Comment by khaliqgant** [comment]
Sorry for the delay here @ComfortablyCoding!

> Ok, I will have a look. What screen size were you checking this on?

1700 x 460

> P.S. Is their some way to run/test this easily on locale? I have been doing it via running local webapp while at the same time running the docker image to have the backend. This is quite tedious.

I typically run the app with a native postgres instance and develop with two commands in separate terminal windows
`npm run dw`
`npm run dwa`


> P.P.S Are their any opinions for mobile view? I believe most of these issues stem from the table having too many columns at small/medium screen size.

We're due for an entire redesign which takes into account mobile. And yes, I agree the tables have too many columns. I think ultimately we'll have to hide some less important columns on smaller screen sizes

**Comment by ComfortablyCoding** [comment]
I have fixed the second issue but looks like some things got pushed that were not supposed to when i did the merge to resolve the conflict with main. I also am not sure why the unit tests are failing. For now I will close the PR and re-do it when I have more time to look into this.

Sorry :)

**Pull request closed without merging**
