### PR TITLE
feat(integrations): add Jira Data Center support

### PR DESCRIPTION
**Pull request by zdhickman**
## Describe your changes

First pass at adding Jira Data Center support. Locally, I was able to set up a new connection and fetch some Jira projects. ~Unsure about how refresh tokens might function~ refresh tokens work OOTB

## Checklist before requesting a review (skip if just adding/editing APIs & templates)
- [ ] I added tests, otherwise the reason is: 
- [ ] I added observability, otherwise the reason is:
- [ ] I added analytics, otherwise the reason is:

### CODE REVIEW

**Comment by bastienbeurier** [comment]
@zdhickman it's possible that the refresh logic already works with your implementation. Do you mind trying to refresh the token from the UI to see if it works? You have to go to the Connections tab, click on the connection, go to the Authorization subtab, press the refresh button next to the access token. Thank you!

**Comment by zdhickman** [comment]
@bastienbeurier just tested this out and was able to refresh the access token!

**Review by bastienbeurier — APPROVED** [review]

**Review by bodinsamuel — APPROVED** [review]
🎯

**Comment by bodinsamuel** [comment]
Thanks for your contribution @zdhickman 🥇

**Pull request merged**
