### PR TITLE
fix(db): remove unnecessary groupBy

### PR DESCRIPTION
**Pull request by bodinsamuel**
## Describe your changes

Contributes to NAN-417

This groupBy seems unnecessary since the `id` column is autoincremented and there is no join. Let me know if there is something else to it. It changes the query plan drastically, from **18s** -> **1.3s**  (92% faster)

## SQL
```sql
EXPLAIN ANALYZE SELECT
	_nango_activity_logs.*
FROM
	nango._nango_activity_logs
WHERE
	environment_id = '3002'
GROUP BY
	_nango_activity_logs.id
ORDER BY
	_nango_activity_logs.timestamp DESC
LIMIT 100;
```

## Before
```sql
Limit  (cost=358861.53..358861.78 rows=100 width=202) (actual time=18470.491..18470.509 rows=100 loops=1)
  ->  Sort  (cost=358861.53..362359.92 rows=1399357 width=202) (actual time=18470.490..18470.498 rows=100 loops=1)
"        Sort Key: ""timestamp"" DESC"
        Sort Method: top-N heapsort  Memory: 78kB
        ->  Group  (cost=0.43..305379.11 rows=1399357 width=202) (actual time=15.258..17391.698 rows=1408037 loops=1)
              Group Key: id
              ->  Index Scan using _nango_activity_logs_pkey on _nango_activity_logs  (cost=0.43..301880.72 rows=1399357 width=202) (actual time=15.255..16423.600 rows=1408037 loops=1)
                    Filter: (environment_id = 3002)
                    Rows Removed by Filter: 3026492
Planning Time: 0.158 ms
Execution Time: 18470.553 ms
```

## After
```sql
Limit  (cost=236936.32..236947.99 rows=100 width=202) (actual time=1345.463..1352.459 rows=100 loops=1)
  ->  Gather Merge  (cost=236936.32..372994.32 rows=1166130 width=202) (actual time=1345.461..1352.441 rows=100 loops=1)
        Workers Planned: 2
        Workers Launched: 2
        ->  Sort  (cost=235936.29..237393.96 rows=583065 width=202) (actual time=1337.875..1337.892 rows=72 loops=3)
"              Sort Key: ""timestamp"" DESC"
              Sort Method: top-N heapsort  Memory: 75kB
              Worker 0:  Sort Method: top-N heapsort  Memory: 75kB
              Worker 1:  Sort Method: top-N heapsort  Memory: 69kB
              ->  Parallel Seq Scan on _nango_activity_logs  (cost=0.00..213651.97 rows=583065 width=202) (actual time=0.038..1053.449 rows=469342 loops=3)
                    Filter: (environment_id = 3002)
                    Rows Removed by Filter: 1008882
Planning Time: 0.145 ms
Execution Time: 1352.513 ms

### CODE REVIEW

**Comment by bastienbeurier** [comment]
Thanks for being thorough with the evaluation of the gains 🙏

**Review by TBonnin — APPROVED** [review]
makes sense. Not sure what the group by was for.

**Comment by khaliqgant** [comment]
I’ll take a look at why that group by was used.

**Comment by bodinsamuel** [comment]
When you have time can you double check @khaliqgant? From what I can see it dates mid 2023, maybe it was useful at first but the database has evolved enough so we can remove it

**Review by khaliqgant — APPROVED** [review]

**Pull request merged**
