### PR TITLE
Only one modal window and handler of manual close

### PR DESCRIPTION
**Pull request by gorets**
I have an interface with a button that should become disable when you click on it and open the authorization window. If the user closes the authorization window himself, then I have no way to find out about this and make the button active again.
The problem with the simultaneous opening of several authorization windows has also been fixed.

### CODE REVIEW

**Comment by bastienbeurier** [comment]
Duplicate of #571

**Comment by bastienbeurier** [comment]
@gorets sorry for the delay here, we haven't had the time to test this feature yet (requires a bit more than usual because it's a critical path + can be browser-specific). We should get to it early next week.

But in any case, thanks a lot for this contribution. We wanted to add this for a while.

**Comment by bastienbeurier** [comment]
@gorets a Nango user pointed out that there's an edge case with Opera that requires a close check: 

```
if (popup?.closed !== false) { ... }
```

Reference: https://stackoverflow.com/a/3291931

Just curious, did you get to test the logic with Opera?

**Comment by gorets** [comment]
> @gorets a Nango user pointed out that there's an edge case with Opera that requires a close check:
> 
> ```
> if (popup?.closed !== false) { ... }
> ```
> 
> Reference: https://stackoverflow.com/a/3291931
> 
> Just curious, did you get to test the logic with Opera?

Yes, I tested my solution in the Opera 102.0.4880.78

This may be relevant for older versions of Opera (not based on Chromium). This comment was made 10 years ago.

**Review by khaliqgant — APPROVED** [review]
Thanks! This seems to work well. I'm going to merge this and then update the messaging some. Thanks for your work here!

**Pull request merged**
